version: "3"
services:

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      PGPORT: ${DATABASE_PORT}
    logging:
      driver: "none"
    restart: unless-stopped
    hostname: ${DOCKER_DB_HOSTNAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    container_name: ${DOCKER_DB_CONTAINERNAME:-2a5-db-development}
    networks:
      - 2a5

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${DOCKER_API_TARGET:-runner}
    depends_on: 
      - db
    hostname: ${DOCKER_API_HOSTNAME:-2a5-api-development}
    image: ${DOCKER_API_IMAGE:-2a5-api-development}
    ports:
      - "${DOCKER_API_PORT:-3000}:3000"
    container_name: ${DOCKER_API_CONTAINERNAME:-2a5-api-development}
    networks:
      - 2a5

volumes:
  db-data:
    name: ${DOCKER_DB_VOLUMENAME:-2a5-db-data-development}

networks:
  2a5:
    name: 2a5