services:

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      PGPORT: ${DATABASE_PORT}
    logging:
      driver: "none"
    restart: unless-stopped
    hostname: ${DOCKER_DB_HOSTNAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    container_name: ${DOCKER_DB_CONTAINERNAME:-2a5-db-development}
    networks:
      - 2a5

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${DOCKER_API_TARGET:-dev}
    depends_on: 
      - db
    environment:
      DATABASE_URL: "postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DOCKER_DB_HOSTNAME}:${DATABASE_PORT}/${DATABASE_NAME}"
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      LINK_PROTOCOL: ${LINK_PROTOCOL}
      LINK_HOSTNAME: ${LINK_HOSTNAME}
      LINK_PORT: ${LINK_PORT}
    hostname: ${DOCKER_API_HOSTNAME:-2a5-api-development}
    ports:
      - "${DOCKER_API_PORT:-3000}:3000"
    container_name: ${DOCKER_API_CONTAINERNAME:-2a5-api-development}
    networks:
      - 2a5
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./lib
          target: /app/lib
        - action: sync
          path: ./pages
          target: /app/pages
        - action: sync
          path: ./public
          target: /app/public
        - action: sync
          path: ./middleware.ts
          target: /app/middleware.ts
        - action: rebuild
          path: package.json

volumes:
  db-data:
    name: ${DOCKER_DB_VOLUMENAME:-2a5-db-data-development}

networks:
  2a5:
    name: 2a5